version: '3.4'
services:
    influxdb:
        container_name: influxdb
        image: quay.io/influxdb/influxdb:v2.0.3
        volumes:
            - influxdbv2:/.influxdbv2
        networks:
            - influxdb-telegraf-net
        ports:
            - "8086:8086"
    influxdb_cli:
        container_name: influxdb_cli
        links:
            - influxdb
        image: quay.io/influxdb/influxdb:v2.0.3
        entrypoint: influx setup --bucket mybucket -t mytoken -o myorg --username=myusername --password=passwordpasswordpassword --host=http://influxdb:8086 -f
        # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service.
        restart: on-failure:10
        networks:
            - influxdb-telegraf-net
        depends_on:
            - influxdb
    telegraf:
        container_name: telegraf 
        image: telegraf
        networks:
            - influxdb-telegraf-net
        links:
            - influxdb
        volumes:
        # Mount for telegraf config
            - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
        depends_on:
            - influxdb_cli
volumes:
    influxdbv2:
networks:
    influxdb-telegraf-net:
        external: true
